# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

reviews = Review.create([
  {title: "Harakiri", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'"},
  {title: "Harakiri", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'"},
  {title: "Harakiri", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'"},
  {title: "Harakiri", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'"},
  {title: "Harakiri", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'"}  
  ])
