# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

reviews = Review.create([
  {title: "Great Move.  A Classic!", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'", category: "film", name: "harakiri", score: 9},
  {title: "Great Move.  A Classic!", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'", category: "film", name: "harakiri", score: 9},
  {title: "Great Move.  A Classic!", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'", category: "film", name: "harakiri", score: 9},
  {title: "Great Move.  A Classic!", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'", category: "film", name: "harakiri", score: 9},
  {title: "Great Move.  A Classic!", text:"I have seen this movie numerous times (at least 10, probably many more), and enjoy it each time. The first couple of times I saw it was right after it came out. It did not have sub-titles, and as my Japanese is not very good, I made some assumptions about the characters, relationships, the plot,etc. When I saw it with sub-titles, I was surprised at how few incorrect assumptions I had made. That I made so few errors is no credit to me, but rather to how well the plot, character development, character relationships, and the overall movie were done.

The movie is not limited to feudal Japan, for it transcends this era. It has lessons, for those who look for this in art. For instance, just one example occurs to me now: It underscores the need for a person to stand on principle, and to maintain their honor, ethics, and dignity, even when those who are the political leaders have long since lost theirs. However for purely entertainment value, the realism, suspense, art, and action could not be better. Words fail to express how this film captivates and entertains. Few films can equal this one. It is a 'must see.'", category: "film", name: "harakiri", score: 9},
{title: "Good!", name: "Star Wars: Episode V - The Empire Strikes Back", score: 8, category: "film", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu libero nisi. Vivamus suscipit cursus semper. Pellentesque orci ipsum, placerat non arcu sit amet, laoreet mollis nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum nec nibh quis tortor consequat porttitor. Proin aliquet odio eu lacus efficitur vehicula. Suspendisse feugiat ante in sapien pulvinar, ac rutrum tortor euismod. Curabitur dictum consequat egestas.

Curabitur faucibus consequat scelerisque. Vestibulum sed nunc lacus. Quisque turpis risus, ultrices et ipsum vitae, mattis vestibulum lorem. Sed posuere leo ac vestibulum congue. Sed et purus dignissim, facilisis eros sit amet, lacinia arcu. Nunc nec risus mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed condimentum elementum elit, eu molestie massa laoreet sit amet. Etiam mollis orci eget eleifend ullamcorper.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed venenatis leo fermentum justo volutpat, vel ultricies ligula tincidunt. Ut ex purus, dapibus in mollis in, convallis tristique orci. Mauris in velit vitae est interdum faucibus. Sed tempus sed est porttitor eleifend. Suspendisse velit est, pharetra sed fermentum a, fermentum non diam. Praesent id mi malesuada, convallis sapien quis, auctor quam. Phasellus auctor vulputate elit malesuada tincidunt. Duis lacinia rutrum eros, eget pulvinar lorem pretium eu. Maecenas malesuada ex a diam lacinia, et volutpat mauris fermentum. Donec vitae aliquet purus, eu luctus risus. Sed nibh urna, aliquam ac lorem a, convallis pulvinar purus. Nunc scelerisque ex quis volutpat dictum. Morbi eu metus egestas, rhoncus velit nec, blandit mi. Sed sed tellus ac justo malesuada venenatis sed maximus ex.

Donec rhoncus arcu et scelerisque convallis. Quisque laoreet tellus at vehicula rutrum. Morbi at efficitur nisl. Maecenas scelerisque malesuada tristique. Aliquam auctor orci est, quis ullamcorper lorem vehicula vitae. Mauris pharetra, dolor at semper fermentum, libero nisl auctor ante, id egestas lectus nisl ac dolor. Donec pharetra feugiat odio, sit amet commodo felis viverra eget. Morbi tincidunt dui in orci tristique, vitae vestibulum sapien vestibulum. Vivamus tempus maximus condimentum. Duis ac magna et nisi iaculis fringilla. Phasellus ut semper felis. Duis at gravida nisi. Nullam condimentum convallis maximus.

Etiam id maximus arcu. Vestibulum venenatis, lorem non aliquam commodo, arcu nibh dapibus mauris, id tincidunt nunc leo quis arcu. Donec eros magna, elementum sed facilisis tempor, pellentesque et nibh. Proin tempor a lectus id consectetur. Duis condimentum porta mi et fringilla. Donec massa est, lobortis sed quam et, sagittis tincidunt leo. Pellentesque non metus dui. Vivamus ultricies magna eu urna tempus fermentum. Morbi eget mauris quis felis mattis rhoncus id at sem. Donec tincidunt nibh nulla, eget faucibus libero rutrum ut. Fusce turpis tortor, congue ac massa at, blandit cursus quam. Curabitur scelerisque varius sapien, vel vestibulum nibh aliquam at. Etiam imperdiet mauris a mi eleifend tempus nec eget urna. Duis eu rhoncus elit. Cras elit nisi, rhoncus condimentum faucibus at, rutrum ut nisi. Aenean elit metus, vestibulum vehicula neque vitae, aliquam sollicitudin mi."},
{title: "Wonderful!", score: 7, text: "Donec rhoncus arcu et scelerisque convallis. Quisque laoreet tellus at vehicula rutrum. Morbi at efficitur nisl. Maecenas scelerisque malesuada tristique. Aliquam auctor orci est, quis ullamcorper lorem vehicula vitae. Mauris pharetra, dolor at semper fermentum, libero nisl auctor ante, id egestas lectus nisl ac dolor. Donec pharetra feugiat odio, sit amet commodo felis viverra eget. Morbi tincidunt dui in orci tristique, vitae vestibulum sapien vestibulum. Vivamus tempus maximus condimentum. Duis ac magna et nisi iaculis fringilla. Phasellus ut semper felis. Duis at gravida nisi. Nullam condimentum convallis maximus.

Etiam id maximus arcu. Vestibulum venenatis, lorem non aliquam commodo, arcu nibh dapibus mauris, id tincidunt nunc leo quis arcu. Donec eros magna, elementum sed facilisis tempor, pellentesque et nibh. Proin tempor a lectus id consectetur. Duis condimentum porta mi et fringilla. Donec massa est, lobortis sed quam et, sagittis tincidunt leo. Pellentesque non metus dui. Vivamus ultricies magna eu urna tempus fermentum. Morbi eget mauris quis felis mattis rhoncus id at sem. Donec tincidunt nibh nulla, eget faucibus libero rutrum ut. Fusce turpis tortor, congue ac massa at, blandit cursus quam. Curabitur scelerisque varius sapien, vel vestibulum nibh aliquam at. Etiam imperdiet mauris a mi eleifend tempus nec eget urna. Duis eu rhoncus elit. Cras elit nisi, rhoncus condimentum faucibus at, rutrum ut nisi. Aenean elit metus, vestibulum vehicula neque vitae, aliquam sollicitudin mi.", name: "In The Mood For Love", category: "film"}
  ])
